import './globals.scss';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Image from 'next/image';
import Link from 'next/link';
import { getUserBySessionToken } from '../database/users';
import LogoutButton from './(auth)/logout/LogoutButton';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user =
    sessionToken && (await getUserBySessionToken(sessionToken.value));


  // console.log('Sessions: ', user);


  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
        <div className="headerLogo">
           <Image src="/logo.png" alt="Company logo" width={140} height={40} />
          </div>

          <div>
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/users-admin">Admin</Link>
            <Link href="/buckets">Buckets</Link>
          </div>
          <div>
            {user ? (
                <>
                 <div>Hello, {user.username} you are logged in.</div>
                 <LogoutButton />
                </>
                ) : (
                  <>
                  <Link href="/register">Register</Link>
                  <Link href="/login">Login</Link>
                  </>
                )}


          </div>

        </nav>
        {children}
        <div>
        <footer className="footer">
          <p>© 2023  MoveForward | All rights reserved.</p>
        </footer>
        </div>

        </body>
    </html>
  )
}
