import './globals.scss';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
        <div className="headerLogo">
           <Image src="/logo.png" alt="Company logo" width={140} height={40} />
          </div>

          <div>
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/buckets">Buckets</Link>
          </div>
        </nav>
        {children}
        <div>
        <footer className="footer">
          <p>© 2023  MoveForward | All rights reserved.</p>
        </footer>
        </div>

        </body>
    </html>
  )
}
